name: CICD

on:
  push:
    branches: [main]

jobs: 
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: delete the folder first if its there
        run: sudo rm -rf ./clonecopy 
      - name: pull the github repo
        run: git clone https://github.com/vscodeislove/express-prisma-docker-aws.git clonecopy
      - name: go to under the directory
        run: cd ./clonecopy && docker-compose up -d
      - name: pwd
        run: pwd
