name: CICD

on:
  push:
    branches: [cicd-docker-ec2]

jobs:        
  deploy:
    runs-on: [ec2runner]
    steps:
      - name: delete the folder first if its there
        run: sudo rm -rf express-prisma-docker-aws
      - name: pull the github repo
        run: git clone https://github.com/vscodeislove/express-prisma-docker-aws.git 
      - name: go to under the directory
        run: cd express-prisma-docker-aws
      - name: run the docker compose up
        run: docker-compose up -d
