name: CICD

on:
  push:
    branches: [main]

jobs: 
  deploy:
    runs-on: self-hosted
    steps:
      - name: pwd 
        run: pwd
      - name: ls
        run: ls
      - name: delete the folder first if its there
        run: sudo rm -rf ./clonecopy
      - name: pwd 
        run: pwd  
      - name: pull the github repo
        run: git clone https://github.com/vscodeislove/express-prisma-docker-aws.git clonecopy
      - name: ls 
        run: ls
      - name: go to under the directory
        run: cd /home/ubuntu/actions-runner/_work/express-prisma-docker-aws/express-prisma-docker-aws/clonecopy
      - name: pwd 
        run: pwd
      - name: run the docker compose up
        run: docker-compose up -d
