name: CICD

on:
  push:
    branches: [main]

jobs: 
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: remove the docker container
        run: docker-compose down
      - name: delete the folder first if its there
        run: rm -rf ./* 
      - name: pwd
        run: ls
      - name: pull the github repo
        run: git clone https://github.com/vscodeislove/express-prisma-docker-aws.git clone
      - name: go to under the directory
        run: docker-compose up -d
        working-directory: ./clone
