name: CICD

on:
  pull_request:
    branches: [dev]
    types: [opened, reopened]

jobs: 
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: build the docker image
        run: docker build .
